name = "sfe-teams"
type = "javascript"

account_id = "794c531a2ec7c23fbdf9477d2cdefa86"
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-08-24"
compatibility_flags = []

kv_namespaces = [{ binding = "KV", id = "d74374b638b44cc4a0f6a1b68c47a5f5" }]

[build]
command = "node scripts/build.js production"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.development.build]
command = "node scripts/build.js development"
[env.development.build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true
