name = "sfe-teams"
type = "javascript"

account_id = "YOUR CLOUDFLARE ACCOUNT ID HERE"
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-08-24"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV", id = "YOUR KV NAMESPACE ID HERE" }
]

[build]
command = "node scripts/build.js production"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.development.build]
command = "node scripts/build.js development"
[env.development.build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true
